#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
cnt=0
while [ $cnt -le 9 ]
do
    if [ $cnt = 3 ]
    then
	echo "bad luck"
	cnt=$(( cnt+1 ))
    elif [ $cnt = 7 ]
    then
        echo "good luck"
	cnt=$(( cnt+1 ))
    else
	echo "Holberton School"
	cnt=$(( cnt+1 ))
    fi
done
