#!/usr/bin/env bash
# This script is displaying "Holberton School" 20 times
cnt=1
while [ $cnt -le 20 ]
do
    case $cnt in
	5) echo "bad luck from China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
    esac
    printf "%s" $cnt
    printf "\n"
    cnt=$(( cnt+1 ))
done
