#!/usr/bin/env bash
# This script gives you information about the holbertonschool file.
file="holbertonschool"
if [ -e ./$file ];
then
    echo "$file file exists"
	if [ ! -s ./$file ];
	then
	    echo "holbertonschool file is empty"
	else
	    echo "holbertonschool file is not empty"
	fi
	if [ ! -d ./$file ];
	then
		echo "$file is a regular file"
	fi
else
    echo "$file file does not exist"
fi
